### ISSUE TITLE
pip install failed 

### ISSUE THREAD

**Issue by CatoDee** [rieder/MASC#23]
Hi Rieder

I installed the amuse module with this tutorial: https://amuse.readthedocs.io/en/latest/install/howto-install-AMUSE.html on my Ubuntu system, and the Python version is 3.11  (a conda environment)

I installed the amuse-framework successfully, but when I ran  “ pip install amuse-masc”, it failed. 

Here is the error message:
> (python3.11) parallels@ubuntu:~$ pip install --use-pep517 amuse-masc
> Collecting amuse-masc
>   Using cached amuse-masc-2023.9.0.tar.gz (15 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Installing backend dependencies ... done
>   Preparing metadata (pyproject.toml) ... error
>   error: subprocess-exited-with-error
>   
>   × Preparing metadata (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [33 lines of output]
>       /tmp/pip-build-env-qk_a5_2x/normal/lib/python3.11/site-packages/setuptools_scm/_integration/setuptools.py:92: UserWarning: version of amuse-masc already set
>         warnings.warn(f"version of {dist_name} already set")
>       Traceback (most recent call last):
>         File "/home/parallels/Software/miniconda3/envs/python3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/home/parallels/Software/miniconda3/envs/python3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/home/parallels/Software/miniconda3/envs/python3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
>           return hook(metadata_directory, config_settings)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-qk_a5_2x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
>           self.run_setup()
>         File "/tmp/pip-build-env-qk_a5_2x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 497, in run_setup
>           super().run_setup(setup_script=setup_script)
>         File "/tmp/pip-build-env-qk_a5_2x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
>           exec(code, locals())
>         File "<string>", line 63, in <module>
>         File "/tmp/pip-build-env-qk_a5_2x/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
>           return distutils.core.setup(**attrs)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-qk_a5_2x/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 146, in setup
>           _setup_distribution = dist = klass(attrs)
>                                        ^^^^^^^^^^^^
>         File "/tmp/pip-build-env-qk_a5_2x/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 318, in __init__
>           self.metadata.version = self._normalize_version(self.metadata.version)
>                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-qk_a5_2x/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 354, in _normalize_version
>           normalized = str(Version(version))
>                            ^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-qk_a5_2x/overlay/lib/python3.11/site-packages/setuptools/_vendor/packaging/version.py", line 200, in __init__
>           raise InvalidVersion(f"Invalid version: '{version}'")
>       setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'False'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> 

I know nothing about how to deal with this problem. I also asked someone to try to install this module, but they also failed. 
Could you help me?  I need this powerful tool

**Comment by risojevicv** [comment]
Here's a quick fix for this issue. Clone the repo, `git clone https://github.com/rieder/amuse-masc.git`. Go to `amuse-masc` directory and edit `setup.py`. Find the line `version=False` and change it to `version="1.0.0"`. Any other version number will also work. Finally, install the package with `pip install .`
